### PR TITLE
ERC721 based Simple loans

### PR DESCRIPTION
**Pull request by adibas03**

### CODE REVIEW

**Comment by adibas03** [comment]
Discussions:
@tspoff @onggunhao 
Few things: (ERC721 peculiar issue)
- `TotalSupply` normally means the number of tokens generated. For an ERC721 token, that would correspond to the number of people who attempted to fund the crowdLoan.
- I am thinking of adding `TotalDebt` to reference the total debt value of the tokens as indicated by `TotalSupply`

**My question:**
Is it better to use the new variable `TotalDebt` or rather hijack the `TotalSupply` to mean the actual debt value of the `DebtTokens`

**Comment by tspoff** [comment]
I think we should use a new variable to track total value of issued debtTokens. 

totalSupply has a standard definition as part of ERC-721 spec:
> A count of valid NFTs tracked by this contract, where each one of them has an assigned and queryable owner not equal to the zero address

I don't know if the total value of issued debt needs to be tracked on the token contract itself, or if something else should track it. I'm generally in favor of keeping token contracts as standard as possible.

**Comment by adibas03** [comment]
@tspoff 
I have added a new folder `debt-contracts`,
The intention is for this to house our contracts, which we are not yet concluded on the location, and can then be import into the desired contracts.
- First I have added **DebtManager** which handles the tracking of the debt value of each one of the `ERC721` tokens. THis is presently imported in the `DebtToken` but we can alway change that, and update the contracts as required.
- Next, I will be adding `RepaymentRouter` which will than be imported into the `crowdloan`

**Comment by tspoff** [comment]
Design looks good to me - I like how you've logically separated the functionality and added interfaces.

**Comment by adibas03** [comment]
@tspoff @onggunhao 
we should probably merge this in,
to allow @onggunhao proceed with tests

**Comment by adibas03** [comment]
closing in favor of updates from **refactor** https://github.com/enabledao/enable-contracts/tree/refactor

**Pull request closed without merging**
